import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";
import { motion } from "framer-motion";

const useCases = [
  { tag: "Product launch planning", title: "Prepare a structured launch workflow", objective: "Organize customer-provided business and media contacts around a defined launch brief.", workflow: "Upload authorized records → review duplicates and quality flags → generate editable campaign-pack drafts → record human approval → prepare eligible records as campaign leads → send later under paid-plan mailbox and safety checks.", control: "The customer reviews all data and content, verifies the sender where live sending is required and decides whether and when any real send occurs." },
  { tag: "Founder-led business development", title: "Keep daily follow-up in one place", objective: "Give a founder or lean commercial team a repeatable way to review contacts and next actions without relying on spreadsheets and inbox memory.", workflow: "Review authorized records → prepare editable drafts → prepare campaign leads → use customer-controlled sending → triage recorded replies → move customer-selected warm contacts into early opportunity records.", control: "Velocity Vision does not identify prospects, promise replies or operate the campaign on the customer's behalf." },
  { tag: "New market test", title: "Separate activity by market or proposition", objective: "Keep customer-provided records, drafts and follow-up organized when testing a new region, vertical or product proposition.", workflow: "Create a dedicated workspace or segment → prepare draft variants in the required campaign language → review local requirements → prepare leads → send only after the applicable paid-plan controls → compare stored outcomes by market.", control: "The customer remains responsible for lawful basis, local marketing rules, sender identity and recipient suitability." },
  { tag: "Existing database review", title: "Review records before any outreach decision", objective: "Bring an existing business database into a structured review process before deciding whether it should be used for commercial activity.", workflow: "Import customer-owned data → map fields → identify duplicates and records needing review → create customer-reviewed segments → keep blocked and suppressed records outside activation preparation.", control: "Velocity Vision does not scrape, sell or provide contact lists, and workspace quality labels are not legal approval." },
  { tag: "Dormant business relationships", title: "Organize a cautious re-engagement review", objective: "Help a customer assess existing business relationships and decide which records may be appropriate for renewed contact.", workflow: "Identify an existing relationship segment → check source and suppression status → prepare editable copy → record approval → prepare a limited lead batch → send later under the current mailbox and plan controls → record replies and opt-outs.", control: "No contact is automatically approved, and Velocity Vision does not guarantee deliverability, compliance, replies or revenue." },
  { tag: "Agency workspaces", title: "Keep client activity isolated", objective: "Allow an agency or fractional team to operate separate client workspaces without mixing client data, drafts or sender decisions.", workflow: "Create one workspace per client → retain isolated data and drafts → prepare client-specific campaign leads → use pooled Campaign Credits for credit-priced AI generation → review account-wide send usage and cross-client stored outcomes.", control: "The agency must have client authority and remains responsible for each client's lawful data, content, sender and activation decisions. Account-wide send visibility is not seat management or cross-seat pooled-send enforcement." },
];

export default function Work() {
  return <>
    <SEO title="Illustrative Software Workflows — Velocity Vision" description="Illustrative customer-controlled workflows for authorized data review, campaign-pack generation, activation preparation, governed sending, replies and stored outcomes." path="/work" />
    <Navbar />
    <main className="pt-20">
      <section className="section-padding bg-hero"><div className="max-w-7xl mx-auto"><motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}><p className="text-accent font-semibold text-sm uppercase tracking-widest mb-4">Illustrative workflows</p><h1 className="text-4xl md:text-6xl font-display font-bold text-primary-foreground mb-6 max-w-4xl">Examples of how customers can configure the workspace</h1><p className="text-primary-foreground/75 text-lg max-w-3xl leading-relaxed">These are hypothetical product workflows, not customer case studies, managed-service offers or performance claims. Actual use depends on the customer's data, plan, configuration, provider readiness, permissions and decisions.</p><p className="text-primary-foreground/70 text-sm max-w-3xl mt-5 leading-relaxed">Velocity Vision does not scrape or sell contact data, send automatically, run A/B tests, attribute revenue automatically, guarantee compliance or promise replies, sales, deliverability, pipeline or revenue.</p></motion.div></div></section>
      <section className="section-padding bg-background"><div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">{useCases.map((useCase, index) => <motion.article key={useCase.title} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: index * 0.08 }} className="group bg-card border border-border/50 rounded-xl p-8 hover:shadow-elevated transition-all"><span className="text-xs font-semibold text-accent uppercase tracking-wider">{useCase.tag}</span><h2 className="font-display font-semibold text-xl text-foreground mt-3 mb-5">{useCase.title}</h2><div className="space-y-4 text-sm"><p><span className="font-semibold text-foreground">Operational objective. </span><span className="text-muted-foreground">{useCase.objective}</span></p><p><span className="font-semibold text-foreground">Software workflow. </span><span className="text-muted-foreground">{useCase.workflow}</span></p><p><span className="font-semibold text-accent">Customer control. </span><span className="text-muted-foreground">{useCase.control}</span></p></div></motion.article>)}</div></section>
    </main><Footer />
  </>;
}
