import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";
import { motion } from "framer-motion";

const useCases = [
  { tag: "Product launch planning", title: "Build the launch campaign from one brief", objective: "Organize customer-provided business and media contacts around a defined launch proposition.", workflow: "Upload authorized records → review duplicates and quality flags → generate the complete editable campaign pack → record human approval → choose activation routes → prepare eligible email leads → manage replies and stored outcomes.", control: "The customer reviews all data and assets, verifies the sender where live email is required and decides whether, where and when anything is activated or distributed." },
  { tag: "Founder-led business development", title: "Keep campaign creation and daily follow-up in one place", objective: "Give a founder or lean commercial team a repeatable way to build campaigns, review contacts and manage next actions without relying on spreadsheets and inbox memory.", workflow: "Review authorized records → build the campaign pack → approve the assets → activate through the chosen route → triage recorded replies → move customer-selected warm contacts into early opportunity records.", control: "Velocity Vision does not identify prospects, promise replies or operate the campaign on the customer's behalf." },
  { tag: "New market test", title: "Separate campaign activity by market or proposition", objective: "Keep customer-provided records, campaign assets and follow-up organized when testing a new region, vertical or product proposition.", workflow: "Create a dedicated workspace or segment → generate the complete pack in the required campaign language → review local requirements → choose activation routes → compare stored outcomes by market.", control: "The customer remains responsible for lawful basis, local marketing rules, sender identity and recipient suitability." },
  { tag: "Existing database review", title: "Review records before any campaign decision", objective: "Bring an existing business database into a structured review process before deciding whether it should be used for commercial activity.", workflow: "Import customer-owned data → map fields → identify duplicates and records needing review → create customer-reviewed segments → keep blocked and suppressed records outside activation preparation.", control: "Velocity Vision does not scrape, sell or provide contact lists, and workspace quality labels are not legal approval." },
  { tag: "Dormant business relationships", title: "Organize a cautious re-engagement campaign", objective: "Help a customer assess existing business relationships and decide which records may be appropriate for renewed contact.", workflow: "Identify an existing relationship segment → check source and suppression status → build editable campaign assets → record approval → prepare a limited lead batch → send later under current mailbox and plan controls → record replies and opt-outs.", control: "No contact is automatically approved, and Velocity Vision does not guarantee deliverability, compliance, replies or revenue." },
  { tag: "Agency workspaces", title: "Keep complete client campaigns isolated", objective: "Allow an agency or fractional team to operate separate client workspaces without mixing client data, campaign packs or sender decisions.", workflow: "Create one workspace per client → retain isolated data and campaign assets → choose client-specific activation routes → use pooled Campaign Credits for credit-priced full-pack generation → review account-wide send usage and cross-client stored outcomes.", control: "The agency must have client authority and remains responsible for each client's lawful data, content, sender and activation decisions. Account-wide send visibility is not seat management or cross-seat pooled-send enforcement." },
];

export default function Work() {
  return <>
    <SEO title="Illustrative Complete Campaign Workflows — Velocity Vision" description="Illustrative customer-controlled workflows for authorized data, complete campaign-pack generation, controlled activation, governed sending, replies and stored outcomes." path="/work" />
    <Navbar />
    <main className="pt-20">
      <section className="section-padding bg-hero"><div className="max-w-7xl mx-auto"><motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}><p className="text-accent font-semibold text-sm uppercase tracking-widest mb-4">Illustrative workflows</p><h1 className="text-4xl md:text-6xl font-display font-bold text-primary-foreground mb-6 max-w-4xl">Examples of complete campaigns customers can configure in the workspace</h1><p className="text-primary-foreground/75 text-lg max-w-3xl leading-relaxed">These are hypothetical product workflows, not customer case studies, managed-service offers or performance claims. Actual use depends on the customer's data, plan, configuration, provider readiness, permissions and decisions.</p><p className="text-primary-foreground/70 text-sm max-w-3xl mt-5 leading-relaxed">Velocity Vision does not scrape or sell contact data, send automatically, run A/B tests, attribute revenue automatically, guarantee compliance or promise replies, sales, deliverability, pipeline or revenue.</p></motion.div></div></section>
      <section className="section-padding bg-background"><div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">{useCases.map((useCase, index) => <motion.article key={useCase.title} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: index * 0.08 }} className="group bg-card border border-border/50 rounded-xl p-8 hover:shadow-elevated transition-all"><span className="text-xs font-semibold text-accent uppercase tracking-wider">{useCase.tag}</span><h2 className="font-display font-semibold text-xl text-foreground mt-3 mb-5">{useCase.title}</h2><div className="space-y-4 text-sm"><p><span className="font-semibold text-foreground">Operational objective. </span><span className="text-muted-foreground">{useCase.objective}</span></p><p><span className="font-semibold text-foreground">Software workflow. </span><span className="text-muted-foreground">{useCase.workflow}</span></p><p><span className="font-semibold text-accent">Customer control. </span><span className="text-muted-foreground">{useCase.control}</span></p></div></motion.article>)}</div></section>
    </main><Footer />
  </>;
}
